// <auto-generated />
using System;
using KnapSoft.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnapSoft.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250323105752_betterdesseed")]
    partial class betterdesseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnapSoft.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Přihlášení, registrace, správa účtů",
                            Name = "Identity",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "ORM a datová vrstva",
                            Name = "Entity Framework",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Online platby + předplatné",
                            Name = "Stripe integrace",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Webová administrace obsahu",
                            Name = "Admin panel",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Email/SMS/push oznámení",
                            Name = "Notifikace",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kalendář, rezervace",
                            Name = "Rezervační systém",
                            Price = 4000m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Vystavování faktur, exporty, DPH",
                            Name = "Fakturační systém",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Backend API pro mobilní nebo externí appky",
                            Name = "REST API",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Oddělení více klientů v jedné aplikaci",
                            Name = "Multitenancy",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Vlastní server včetně nastavení a zabezpečení",
                            Name = "Hosting (VPS)",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Nasazení na Azure (App Service + SQL + SMTP)",
                            Name = "Hosting (Azure)",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Offline režim, Add to Home screen, service worker",
                            Name = "PWA podpora",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 13,
                            Description = "SMTP, SendGrid integrace",
                            Name = "Email systém",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Základní SEO, OpenGraph, sitemap",
                            Name = "SEO optimalizace",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 15,
                            Description = "2 hodiny měsíčně, běžná priorita",
                            Name = "Základní technická podpora",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Reakce do 24h, až 5 hodin měsíčně",
                            Name = "Prioritní podpora",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Podpora více platebních metod",
                            Name = "Integrace platební brány",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Manuály a návody pro klienta",
                            Name = "Uživatelská dokumentace",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 19,
                            Description = "1-2 hod videohovor/online školení",
                            Name = "Školení na míru",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 20,
                            Description = "CSV, Excel, PDF import/export",
                            Name = "Export/Import dat",
                            Price = 2200m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Role a oprávnění",
                            Name = "Správa uživatelských rolí",
                            Price = 2500m
                        });
                });

            modelBuilder.Entity("KnapSoft.Models.Solution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Solutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ideální pro malé firmy a živnostníky. Jednoduchá prezentace služeb, kontaktní formulář a vlastní správa obsahu bez složitého ovládání.",
                            MonthlyPrice = 1200m,
                            Name = "Jednoduchý web",
                            Price = 8000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Moderní mobilní web, který funguje i offline. Vaši zákazníci si jej mohou přidat na plochu jako aplikaci. Skvělé pro rychlé objednávky, rezervace nebo interní systémy.",
                            MonthlyPrice = 1500m,
                            Name = "PWA aplikace",
                            Price = 12000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Základní e-shop pro menší prodej. Zahrnuje správu produktů, košík, online platby a přehledné objednávky. Vhodné pro začínající prodejce.",
                            MonthlyPrice = 1800m,
                            Name = "Eshop Basic",
                            Price = 18000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Rozšířený e-shop pro rostoucí podnikání. Navíc nabízí fakturaci, přehledy pro účetní, exporty a více uživatelských práv. Vhodné pro firmy, které chtějí růst.",
                            MonthlyPrice = 2200m,
                            Name = "Eshop Plus",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kompletní řešení pro rozvoz jídel nebo zboží. Zákazníci objednají online, vy dostanete přehled o objednávkách a trasách. Včetně notifikací a plateb.",
                            MonthlyPrice = 2500m,
                            Name = "Rozvozový systém",
                            Price = 29000m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vše, co potřebujete pro rychlý provoz: přehled objednávek, pokladní režim, reporty a možnost tisku účtenek. Ideální pro bistra a fastfoody.",
                            MonthlyPrice = 2800m,
                            Name = "Systém pro fastfoody",
                            Price = 32000m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Správa menu, rezervace stolů a denní reporty. Jednoduché ovládání pro personál a přehledné rozhraní pro zákazníky. Připraveno pro provoz s obsluhou.",
                            MonthlyPrice = 2500m,
                            Name = "Systém pro kavárny",
                            Price = 28000m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Umožněte svým zákazníkům přihlásit se, sledovat objednávky, stahovat faktury nebo komunikovat. Vhodné i pro správu dokumentů a firemních služeb.",
                            MonthlyPrice = 1900m,
                            Name = "Portál pro klienty",
                            Price = 22000m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Profesionální systém pro provoz více firem nebo poboček pod jednou aplikací. Každý klient má své vlastní prostředí. Ideální pro B2B platformy nebo franšízy.",
                            MonthlyPrice = 3200m,
                            Name = "Multitenant SaaS",
                            Price = 38000m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Prémiové řešení s cloudovým hostingem na Azure, offline režimem, zákaznickou dokumentací a prioritní technickou podporou. Vhodné pro náročné projekty a firmy s růstem.",
                            MonthlyPrice = 3500m,
                            Name = "Full Azure PWA",
                            Price = 45000m
                        });
                });

            modelBuilder.Entity("KnapSoft.Models.SolutionProduct", b =>
                {
                    b.Property<int>("SolutionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("SolutionId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("SolutionProducts");

                    b.HasData(
                        new
                        {
                            SolutionId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            SolutionId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            SolutionId = 1,
                            ProductId = 4
                        },
                        new
                        {
                            SolutionId = 1,
                            ProductId = 14
                        },
                        new
                        {
                            SolutionId = 1,
                            ProductId = 10
                        },
                        new
                        {
                            SolutionId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            SolutionId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            SolutionId = 2,
                            ProductId = 4
                        },
                        new
                        {
                            SolutionId = 2,
                            ProductId = 5
                        },
                        new
                        {
                            SolutionId = 2,
                            ProductId = 12
                        },
                        new
                        {
                            SolutionId = 2,
                            ProductId = 11
                        },
                        new
                        {
                            SolutionId = 3,
                            ProductId = 1
                        },
                        new
                        {
                            SolutionId = 3,
                            ProductId = 2
                        },
                        new
                        {
                            SolutionId = 3,
                            ProductId = 3
                        },
                        new
                        {
                            SolutionId = 3,
                            ProductId = 4
                        },
                        new
                        {
                            SolutionId = 3,
                            ProductId = 7
                        },
                        new
                        {
                            SolutionId = 3,
                            ProductId = 10
                        },
                        new
                        {
                            SolutionId = 4,
                            ProductId = 1
                        },
                        new
                        {
                            SolutionId = 4,
                            ProductId = 2
                        },
                        new
                        {
                            SolutionId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            SolutionId = 4,
                            ProductId = 4
                        },
                        new
                        {
                            SolutionId = 4,
                            ProductId = 5
                        },
                        new
                        {
                            SolutionId = 4,
                            ProductId = 7
                        },
                        new
                        {
                            SolutionId = 4,
                            ProductId = 20
                        },
                        new
                        {
                            SolutionId = 4,
                            ProductId = 21
                        },
                        new
                        {
                            SolutionId = 4,
                            ProductId = 10
                        },
                        new
                        {
                            SolutionId = 5,
                            ProductId = 1
                        },
                        new
                        {
                            SolutionId = 5,
                            ProductId = 2
                        },
                        new
                        {
                            SolutionId = 5,
                            ProductId = 3
                        },
                        new
                        {
                            SolutionId = 5,
                            ProductId = 4
                        },
                        new
                        {
                            SolutionId = 5,
                            ProductId = 5
                        },
                        new
                        {
                            SolutionId = 5,
                            ProductId = 7
                        },
                        new
                        {
                            SolutionId = 5,
                            ProductId = 17
                        },
                        new
                        {
                            SolutionId = 5,
                            ProductId = 20
                        },
                        new
                        {
                            SolutionId = 5,
                            ProductId = 10
                        },
                        new
                        {
                            SolutionId = 6,
                            ProductId = 1
                        },
                        new
                        {
                            SolutionId = 6,
                            ProductId = 2
                        },
                        new
                        {
                            SolutionId = 6,
                            ProductId = 3
                        },
                        new
                        {
                            SolutionId = 6,
                            ProductId = 4
                        },
                        new
                        {
                            SolutionId = 6,
                            ProductId = 7
                        },
                        new
                        {
                            SolutionId = 6,
                            ProductId = 20
                        },
                        new
                        {
                            SolutionId = 6,
                            ProductId = 21
                        },
                        new
                        {
                            SolutionId = 6,
                            ProductId = 10
                        },
                        new
                        {
                            SolutionId = 7,
                            ProductId = 1
                        },
                        new
                        {
                            SolutionId = 7,
                            ProductId = 2
                        },
                        new
                        {
                            SolutionId = 7,
                            ProductId = 4
                        },
                        new
                        {
                            SolutionId = 7,
                            ProductId = 5
                        },
                        new
                        {
                            SolutionId = 7,
                            ProductId = 6
                        },
                        new
                        {
                            SolutionId = 7,
                            ProductId = 7
                        },
                        new
                        {
                            SolutionId = 7,
                            ProductId = 20
                        },
                        new
                        {
                            SolutionId = 7,
                            ProductId = 21
                        },
                        new
                        {
                            SolutionId = 7,
                            ProductId = 10
                        },
                        new
                        {
                            SolutionId = 8,
                            ProductId = 1
                        },
                        new
                        {
                            SolutionId = 8,
                            ProductId = 2
                        },
                        new
                        {
                            SolutionId = 8,
                            ProductId = 4
                        },
                        new
                        {
                            SolutionId = 8,
                            ProductId = 5
                        },
                        new
                        {
                            SolutionId = 8,
                            ProductId = 7
                        },
                        new
                        {
                            SolutionId = 8,
                            ProductId = 8
                        },
                        new
                        {
                            SolutionId = 8,
                            ProductId = 10
                        },
                        new
                        {
                            SolutionId = 9,
                            ProductId = 1
                        },
                        new
                        {
                            SolutionId = 9,
                            ProductId = 2
                        },
                        new
                        {
                            SolutionId = 9,
                            ProductId = 4
                        },
                        new
                        {
                            SolutionId = 9,
                            ProductId = 5
                        },
                        new
                        {
                            SolutionId = 9,
                            ProductId = 7
                        },
                        new
                        {
                            SolutionId = 9,
                            ProductId = 8
                        },
                        new
                        {
                            SolutionId = 9,
                            ProductId = 9
                        },
                        new
                        {
                            SolutionId = 9,
                            ProductId = 10
                        },
                        new
                        {
                            SolutionId = 10,
                            ProductId = 1
                        },
                        new
                        {
                            SolutionId = 10,
                            ProductId = 2
                        },
                        new
                        {
                            SolutionId = 10,
                            ProductId = 4
                        },
                        new
                        {
                            SolutionId = 10,
                            ProductId = 5
                        },
                        new
                        {
                            SolutionId = 10,
                            ProductId = 7
                        },
                        new
                        {
                            SolutionId = 10,
                            ProductId = 12
                        },
                        new
                        {
                            SolutionId = 10,
                            ProductId = 11
                        },
                        new
                        {
                            SolutionId = 10,
                            ProductId = 13
                        },
                        new
                        {
                            SolutionId = 10,
                            ProductId = 18
                        },
                        new
                        {
                            SolutionId = 10,
                            ProductId = 19
                        },
                        new
                        {
                            SolutionId = 10,
                            ProductId = 15
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KnapSoft.Models.SolutionProduct", b =>
                {
                    b.HasOne("KnapSoft.Models.Product", "Product")
                        .WithMany("SolutionProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnapSoft.Models.Solution", "Solution")
                        .WithMany("SolutionProducts")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnapSoft.Models.Product", b =>
                {
                    b.Navigation("SolutionProducts");
                });

            modelBuilder.Entity("KnapSoft.Models.Solution", b =>
                {
                    b.Navigation("SolutionProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
